import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { GeistSans } from 'geist/font/sans'
import CustomProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teams Phone Implementer in Thailand",
  description: "Generated by SunCTI TECHNOLOGY INNOVATION CO., LTD.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CustomProvider>
      <html lang="en">
        <body suppressHydrationWarning={true} className={GeistSans.className}>
          {children}
        </body>
      </html>
    </CustomProvider>
  );
}
