import { Roboto } from "next/font/google";
import "./globals.css";
import COMP_NAVBAR from "@/components/navbar";
import FOOTER from "@/components/footer";

const roboto = Roboto({
  weight: ['100','300','400','500','700','900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        <FOOTER/>
        </body>
    </html>
  );
}
